### ISSUE TITLE
Sakriti paginaciju, ako nema ucenika

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#11]
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/d389e72a-64e1-4006-98b8-c38cdf8c86c3)

@Faariis

**Comment by Faariis** [comment]
Urađeno za home, user, admin.

**Comment by Faariis** [comment]
![Screenshot (311)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/3fdf2c63-1f85-4520-acc2-e735d9fa9d26)

Closes #11

**Comment by aheacon** [comment]
Ja nisam dobio kao sto si ti dobio. DObio sam ovako
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/2e575c89-10db-431f-908a-91f7ea90562c)


Dugme koje nema nikakvog smisla. Vidi #10 da se izbrise.

**Comment by Faariis** [comment]
![Screenshot (311)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/06f58d0e-c4a4-4ff4-84a5-67f262bdea9f)
