### ISSUE TITLE
Kosmeticki fixovi za responsive

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#13]
1. Popraviti prikaz dugmadi - overlaping sa borderom ne smije biti
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/fa75e3d2-755a-46a1-a6b1-571b6fdda9ec)

2. Umjesto `Pozicija` treba biti `Trenutna pozicija`

3. Dodati nav `Pocetna` na responsivu (trenutno nema nacina da se vrati nazad) (za sve endpointe)
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/35862cb8-c1d5-43d9-8276-8b65df03ccf6)
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/5d5625f6-da50-4177-b2cb-cdb7157e7fa4)

**Comment by Faariis** [comment]
1. Uradio sam nešto ali opet ne znam kako će kod Vas izgledat jer kod mene normalno izgleda (za sve uređaje).
2. Trenutna pozicija ima previše karaktera što smeta kod responsive designa.
3. Dodao sam početna za responsive design.

**Comment by Faariis** [comment]
2. Trenutna pozicija
![Screenshot (309)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/9150ee23-1774-4860-a5aa-d4e5d30a05a0)
3. Početna za mobitele
![Screenshot (310)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/4af18659-a07d-4d55-a959-155a81af1ec0)

**Comment by aheacon** [comment]
Super.
Ima jos jedan edge-case, ali mozemo se vratiti na to 
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/10c1e85a-37f1-471d-b8b0-4dba7b4d7b7f)

**Comment by aheacon** [comment]
Da bismo dobili na prostoru, za sljedeci put (ili ako nije predugo sada) `Ime i prezime` ukloniti iz tabele, nego staviti iznad u poseban div, a ostaviti Trenutna poziciaj i smjer + dugmad. Za vise ucenika sa istim imenom odvojiti crtom.
Mozda @IsmetGlumcevic  ima neku ideju kako to napraviti bolje/brze?

**Comment by Faariis** [comment]
Zadnji moj commit treba popravit ove neke edge-cases.

**Comment by aheacon** [comment]
Nastavlja se na #39
