### ISSUE TITLE
Sakriti header tabele ukoliko ucenik nije odabran

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#14]
Header ne bi smio da se vidi na pocetku, tek pri kliku (eventu).

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/c2278dae-4261-440e-bbdc-9db92f64e853)

**Comment by Faariis** [comment]
Sakrio sam.

**Comment by Faariis** [comment]
![Screenshot (308)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/6c490d89-aa5d-4563-ab1f-9ebbda7fe8c5)
![Screenshot (309)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/5f1359a1-64de-4beb-b53d-4fb0d35c2db5)

Closes #14

**Comment by aheacon** [comment]
Super.
