### ISSUE TITLE
Dodati header za smjerove na pocetnoj stranici

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#15]
Dodati `Naziv smjera` i `Trajanje` na pocetnoj stanici, a izbrisati `Trajanje` iz svakog reda. Izbrisati `Lista smjerova`

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/5a400c26-867a-4e10-9e72-1a5b74b75b1b)

@Faariis

**Comment by Faariis** [comment]
Urađeno

**Comment by Faariis** [comment]
![Screenshot (307)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/a531c6dc-f860-4791-856d-1d5fab8113a9)

Closes #15

**Comment by aheacon** [comment]
Edge-case za responsive (vratit se poslije ako bude trebalo)
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/e0b0c6ac-39a7-4092-a1d5-eb760e8fc7b6)

**Comment by Faariis** [comment]
Commit Vertical aligment and responsive edge-cases trebao bi ovo popravit.

**Comment by aheacon** [comment]
@Faariis  jel ovo gotovo>?

**Comment by Faariis** [comment]
@aheacon 

Laptop
![Screenshot (350)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/0274c42d-bbea-4941-9a25-8cc2cae3a299)

Mali laptop
![Screenshot (351)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/05316cdd-7ddc-41c1-a701-7aa58ae52fae)

Tablet
![Screenshot (352)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/77be1324-6282-4b54-909d-0c2575098755)
