### ISSUE TITLE
Izbrisati nepotrebne informacije

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#16]
Izbrisati text box `Unesite ime i prezime učenika` a u place holder staviti `Unesite ime i/ili prezime`

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/e4b1b27e-5b69-462d-88aa-2b43b580ee9b)

**Comment by Faariis** [comment]
Urađeno

**Comment by Faariis** [comment]
![Screenshot (306)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/c2a0489f-5f80-49c7-8e19-ae5ab5b29c1b)

Closes #16

**Comment by aheacon** [comment]
Bravo.
