### ISSUE TITLE
Prebaciti "back" dugme na lijevu stranu

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#17]
Trenutno je dugme na krajnjoj desnoj strani diva, obicno su ova dugmad na suprotnoj strani

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/ca838ef0-0438-45eb-ada9-d22e57953d64)

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/0645a93b-e566-4064-b8ac-31cd99bee8d1)

Mozes li napraviti poseban div samo za ove kontrole, a ispod (ili iznad) toga da bude `Lista ucenika: RTIA` (primijeti `:`)

**Comment by Faariis** [comment]
Regular:
![Screenshot (304)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/5bfdafa9-b01d-42b3-a69d-ed7752b79c6b)
Mobitel:
![Screenshot (305)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/46bd93a7-e4be-4ba9-8ea0-6de7acbedcb2)

Closes #17

**Comment by aheacon** [comment]
Nastavlja se u #35
