### ISSUE TITLE
Odvoji text box od dugmeta

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#18]
Ovo ovdje treba odvojiti, posebno button back `<`, a posebno text box: `Smjer: RTIA` (koji treba centrirati)

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/c2259df4-b69a-4e37-87f5-f736bc4c9193)

**Comment by Faariis** [comment]
Odvojio sam ih i za tableDetails.js i studentDetails.js

**Comment by Faariis** [comment]
![Screenshot (302)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/7b39f69f-c190-4719-b51c-c5bb16437eaf)

Closes #18

**Comment by aheacon** [comment]
Super.
