### ISSUE TITLE
Izbaci sliku nastavnika i dodaj mu login ime

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#19]
- Super admin
Trenutno nastavnik nema sliku (nemamo u bazi), izbaciti sliku, a pored toga staviti login informacije (bar ime), pored `Register`.

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/42d1099c-fbbe-4494-821e-32a9f0e5452c)

Pored toga dodati dugme `Log out`.

- Nastavnik
Isto vazi i za  nastavnika

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/1756dcb8-21d5-48e5-8d34-f6ffb68c6d91)

**Comment by Faariis** [comment]
Uklonio sam sliku, stavio sam ime nastavnika/admina. Na admin panelu uklonio sam ime register (nema nikakve funkcije).

**Comment by Faariis** [comment]
![Screenshot (300)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/ca389e12-0b0c-4246-ad10-484e4f5e0453)
![Screenshot (301)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/a25cb1b9-18f2-49c1-b3ea-89498926853c)

Closes #19

**Comment by aheacon** [comment]
Citaj taskove molim te.
```
Pored toga dodati dugme Log out.
```

**Comment by Faariis** [comment]
![Screenshot (342)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/65c930de-99e1-4ddd-b0f9-c6a0fe08149c)
Ide ime pa Log out

**Comment by aheacon** [comment]
Super
