### ISSUE TITLE
Nastavnik sa admin opcijama, ne moze dodati ucenika :S

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#20]
Dodati mogucnost dodavanja ucenika

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/d3b2a0a5-9bbc-4832-9cdd-f6843ab595dd)

Dodaj mu tab `Nastavnik opcije` kao i za regularnog nastavnika

![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/11ef48aa-e62e-45e8-953c-e062c3aebb39)

**Comment by Faariis** [comment]
Dodao sam sve nastavnik opcije za admina.

**Comment by Faariis** [comment]
![Screenshot (297)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/0d7926ee-3b34-4032-aa1a-ef3d9f29a609)
![Screenshot (298)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/dc080f00-a8be-468d-b07d-fff461dd85eb)
![Screenshot (299)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/3d57f77e-3f85-4983-b0a0-1d2e8750f438)

Closes #20

**Comment by aheacon** [comment]
Dodavanje i dalje ne radi, ja nisam uspio da dodam novog ucenika.
@Faariis

**Comment by Faariis** [comment]
Promjene:

1. Broj mora početi sa +387, njegova dužina je od 9 do 12 karaktera (pratio sam bekend). Sada se broj može unijeti bez razmaka, a dodao sam mogućnost sa razmacima (whitespaces). Razmaci se ne spadaju u dužinu brojeva (karaktera) i na taj način neće se podići error o dugom broju. #26
![Screenshot (324)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/0e4930dd-4349-4961-b2f6-a74ed876dc5e)

2. Prije nije bilo ograničenje za domenu emaila. Dolazilo je do greške ako se ne doda tačka i barem dva karaktera nakon tačke. Sada sam stavio error ako nema tačke na kraju i ako je dužina karaktera nakon tačke < 2. 
![Screenshot (329)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/34c00f44-053a-4267-bb2d-cbd1a6d4df4f)
![Screenshot (330)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/76a4e168-5060-43e0-9e19-4ac36195568e)
![Screenshot (331)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/f46b3f9a-c072-4ea7-ac7d-d1ae63b38be8)
