### ISSUE TITLE
Prelaskom na Nastavnik opcije dobijemo netacnu poruku

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#21]
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/ab057983-90e7-49df-96a3-09878cfbcadc)

**Comment by Faariis** [comment]
Urađeno.

**Comment by Faariis** [comment]
![Screenshot (294)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/48c96936-89d3-446d-a048-a104a5fca785)

Closes #21
