### ISSUE TITLE
Nastavnik trenutno ne moze vidjeti ucenike za edit

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#22]
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/4524d4ab-e929-4c15-b7da-b024b6388ae9)

**Comment by Faariis** [comment]
Ovo sam riješio. Dodao sam novu rutu i sada je podržana paginacija. Otvorio sam issue novi gdje treba dodati da ruta vrati email i telefon (trenutno koristim fali na tim pozicijama). Edit i delete ne rade jer rute student-list/<int:school_id>/ i student-list/<int:pk>/ imaju konflikt. Ja sam promjenio da student-list/<int:school_id>/ bude student-list/<int:school_id>/students/ (otvorio sam issue vezano za to). Kada se to namjesti radit će delete i edit na liver serveru.

**Comment by Faariis** [comment]
![Screenshot (294)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/dc914adc-58b9-45dd-b355-769303a91a91)
![Screenshot (295)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/c3b78a4c-19a6-4683-84c4-e6921928a7ad)
![Screenshot (296)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/3719a4b9-07ff-4265-9f5e-9961f4cd47a4)

Closes #22

**Comment by aheacon** [comment]
@Faariis  molim te testiraj svoje promjene prije nego sto zatrazis review.

Edit ucenika i dalje ne radi. Pored toga sve sto se odnosi na neke stvari koje smo uradili u prethodnim issues primijeni na sve ostale page-ove. Npr. na ovoj stranici i dalje je back dugme na desnoj strani, prebaci ga na lijevu stranu.
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/e0638c28-a17a-40d2-a7be-f3fa020f1881)

**Comment by aheacon** [comment]
Super
