### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by Faariis** [aheacon/school_enrollment_frontend#25]
@IsmetGlumcevic  dugme detalji kada se učenik pretražuje na ListStudentsHome i dugme detalji na ListStudentsPerCourse vode na istu stranicu tj. studentDetails.js. Da li je moguće da ako se dođe sa ListStudentsHome i pritisne back da se vrati na ListStudentsHome, a ako dođe sa ListStudentsPerCourse vrati na ListStudentsPerCourse.  

Slikoviti prikaz: 

## 1. Za listStudentsHome!

**Trenutno stanje**

Kada odem na pretragu učenika -> komparaciju -> detalji (npr. smjer GT)

![Screenshot (315)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/230db145-f6a1-46a7-a3f0-ac40ab2119c8)

Odvest će me na studentDetail.js tj. individualnu tabelu

![Screenshot (316)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/cd9b3bcd-cc99-4f0d-b6b7-43a36e443d09)

Kada pritisnem back (<) vrati me na listStudentsPerCourse.js

![Screenshot (317)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/cc15de36-b792-4ee4-b31c-afc876e6d06b)

**Šta želim da se postigne**

![Screenshot (315)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/5c053003-bb86-4778-8fad-9fe5ff69cbb3)

![Screenshot (316)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/8cd16144-86a3-4ef5-8b2c-0ace37c898e6)

Kada se pritisne back (<) da opet vrati na ovo

![Screenshot (315)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/77dafd54-2397-44c0-a5ac-2eead5392b13)

## 2. Za listStudentsPerCourse!

Ovdje dobro radi pa se ne mora mijenati
Ako odemo na detalji odvede nas na studentDetail.js (individualna tabela)
![Screenshot (318)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/68e733dc-1d18-4f54-bab5-63ac8bcde334)
![Screenshot (320)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/4633ddae-7b3b-4ad1-9b9a-a61e6fe3abc0)

Kada pritisnemo back vrati nas na listStudentsPerCourse

![Screenshot (318)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/5af49b62-b34d-405b-bf13-c19f9c110393)

**Comment by aheacon** [comment]
Nastavlja se u #35
