### ISSUE TITLE
Popraviti unos predmeta responsive do neke mjere

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#28]
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/e91bad93-8900-4da4-b5fe-db472c03a41d)

Na laptopu^

**Comment by Faariis** [comment]
Meni ovo izgleda sve uredno na mom ekranu (gledam za tablet, mali laptop, laptop). Tako da ja ne vidim ovo da bježi.

**Comment by aheacon** [comment]
I dalje postoji zatvaram ovaj dokumentovan u #41
