### ISSUE TITLE
Svako polje treba biti nezavisno

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#29]
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/137c3356-9fd2-49d6-a23f-e448e27fe21c)

redni broj ispod rednog broja, smjer ispod smjera, a ne da su zavisni od broja slova roditelja. 
Napravi kako treba sa divovima.

**Comment by Faariis** [comment]
![Screenshot (344)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/90d6a387-c57c-4582-a0af-8ca5016224ec)
