### ISSUE TITLE
Dodati datum za tranziciju i oznaciti nekom bojom koji je zadnji smjer

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#30]
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/750c57b1-bd4a-4330-abe3-b2f07d840442)
dodati jos jednu kolonu datum (prosiriti backend).

**Comment by Faariis** [comment]
![Screenshot (336)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/3f0f6699-8389-4521-80a8-9582188ab945)
