### ISSUE TITLE
Pogresni smjerovi

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#31]
Trenutno imamo 2 ucenika istog imena na RTIA I EL
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/f7708656-8d6e-4321-bf6f-3a87e9c9d636)

Medjutim tranzicija ne pokazuje tako
Za RTIA: 
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/cf0a9f12-723e-4e2c-a190-1772cdf5675e)

Za EL:
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/98bca1fd-cc19-42ee-83b2-6e6b9a6cf16d)

**Comment by Faariis** [comment]
Ovo je do bekenda. Nije do frontenda.

**Comment by Faariis** [comment]
Trenutno imamo 2 ucenika istog imena na RTIA I EL
![Screenshot (334)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/5894caed-4551-4a17-930c-d2ef50cc82bf)
![Screenshot (335)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/d831b665-666f-47c5-a8f3-bb240c469a43)
![Screenshot (336)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/bb3e203e-821b-4b48-bd3c-edc66c442b0c)

**Comment by aheacon** [comment]
@Faariis  potvrdi da radi i zatvori.

**Comment by Faariis** [comment]
@aheacon Popravljeno :)

**Comment by an3l** [comment]
Zatvaram, vjerujem na rijec.
