### ISSUE TITLE
Greška kod tabelarnog prikaza

### ISSUE THREAD

**Issue by kadusicadi** [aheacon/school_enrollment_frontend#32]
Nakon pokušaja ulaska u tabelarni prikaz za smjer **RTIA** dolazi do sljedeće greške:

![greska](https://github.com/aheacon/school_enrollment_frontend/assets/154362609/84a0e2d1-1f94-4ef9-b9cd-252f6df9ca52)
Jedna solucija za pravilan rad aplikacije je pokretanje komande:

```batch
npm install @react-pdf/renderer
```

**Comment by Faariis** [comment]
@aheacon kada budete pokretali live server i odete na tabelarni prikaz, ako pokaže ovo, problem je do react-pdf/renderer.
Onda se treba pokrenuti: npm install @react-pdf/renderer da updejtuje verziju.

**Comment by aheacon** [comment]
Ovo je zavrseno.
