### ISSUE TITLE
Dodaj footer

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#34]
Dodaj molim te footer sa godinom  i copyright na Eacon
@Faariis

**Comment by Faariis** [comment]
![Screenshot (349)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/b8dd2e99-308a-42c2-9810-9410005a87e4)

@aheacon da li može ovako

**Comment by aheacon** [comment]
Super
