### ISSUE TITLE
Lijevo poravnanje

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#35]
Za mobitele, prebaci "Pocetna" na lijevo i implementiraj da radi, jer trenutno ne radi.
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/2314f7a6-a035-4e38-9abb-64ccc8e1ed89)

**Comment by Faariis** [comment]
![Screenshot (355)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/c2002b5a-083d-43d7-8645-438e8131cf2b)

@aheacon početna preusmjeravanje radi kada smo na drugom url-u. Ako je na url-u "/" što je spisak smjerova i pretraživanje to se gleda kao isti url "/" tako da dugme ne radi ništa.

**Comment by an3l** [comment]
Popravi da radi za slucaj koji je komentarisan - prosiri malo screen i vidjet ces da ne radi.

**Comment by aheacon** [comment]
Prosiri screen i popravi sto ne radi.
