### ISSUE TITLE
Pagination i za ucenike, kao i za nastavnike

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#36]
Trenutno ucitvamo nove ucenike
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/db272671-9395-4d49-a9bb-8827cb3a543b)

Doraditi da ih prikazujemo po stranici (pagination) kao sto je uradjeno za listu ucenika koje nastavnik moze da vidi. 
Napomena: ovo uraditi nakon sto se doda backend endpoint.
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/b4c4b15b-66f6-429e-bf8c-362270c603da)

**Comment by aheacon** [comment]
Koji endpoint koristis ovdje?

**Comment by Faariis** [comment]
@aheacon student-list/<int:school_id>/<str:_course_code>/<int:start>/<int:num>/

**Comment by Faariis** [comment]
@aheacon Odradio sam istu paginaciju kao i za nastavnike.

![Screenshot (400)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/e001abd4-921f-44a3-93e7-3bbafdf917c3)
![Screenshot (401)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/358e1659-be67-4a5f-9d5f-a87ec8cc570e)
