### ISSUE TITLE
Dodati trenutni smjer na tranzicije

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#40]
- Omoguciti da trenutni smjer bude vidlji i na tranziciji.
- http://localhost:3535/user/pupils/34/edit
- Trenutno ne vidimo smjer ucenika, ukoliko nema nikakve tranzicije
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/4e615a07-2b67-4551-a9c4-f146f05c4b29)

**Comment by Faariis** [comment]
![Screenshot (356)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/fe9110da-18db-4f63-b7ab-e170054c85a1)

@aheacon kada nema tranzicije

**Comment by aheacon** [comment]
Ok, koji commit ?

**Comment by Faariis** [comment]
[Added current course when there is no transition](https://github.com/aheacon/school_enrollment_frontend/pull/46/commits/9b71c8e897ba6d894f601cd063f0d83e974b242f)
