### ISSUE TITLE
Dodati polje datum upisa ucenika za nastavnike

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#44]
- U tabeli ima polje `date_of_enrollment` iskoristiti to polje za prikaz datuma upisa ucenika
- http://localhost:3535/admin/listStudents
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/20cf0eaf-b1fc-4b8e-b760-3b996bb3b805)

- Isto polje datum upisa dodati za ostale korisnike
http://localhost:3535/home/AT
![image](https://github.com/aheacon/school_enrollment_frontend/assets/45823316/6897145f-788a-481f-8a33-7f9f3f7c412d)

**Comment by Faariis** [comment]
![Screenshot (358)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/a09a6179-903b-4570-9bfe-7a5ec5e4b8d2)

@aheacon dodao sam datum za admin i nastavnika panel
